SELECT CITY, LENGTH(CITY) AS CityLength
FROM STATION
WHERE CITY=(
    SELECT CITY
    FROM STATION
    ORDER BY LENGTH(CITY), CITY
    LIMIT 1
    )
UNION ALL
SELECT CITY, LENGTH(CITY) AS CityLength
FROM STATION
WHERE CITY = (
    SELECT CITY
    FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY
    LIMIT 1
    );